name: snyk vulnerabilities tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read 
    strategy:
      matrix:
        container: [ml-tagger]
    steps:
      - uses: actions/checkout@v2

      - name: Build container ${{ matrix.container }}
        run: cd build/${{ matrix.container }} && make dbuild version=latest

      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: airenas/${{ matrix.container }}:latest
          args: --file=build/${{ matrix.container }}/Dockerfile

      - name: Make sarif file copy
        run: mv snyk.sarif snyk-${{ matrix.container }}.sarif

      - name: Upload snyk ${{ matrix.container }} result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-${{ matrix.container }}.sarif
          category: ${{ matrix.container }}-analysis
